pmd 6

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -90,8 +90,28 @@ jobs:
           else
             echo "No PMD issues found in the Apex code."
             cat pmd-report.txt
-          fi  
+          fi 
+      # Run apex test only if pmd check is successful, otherwise this will not execute since we used EXIT 1 above on error
+      - name: Run Apex Tests
+        run: |
+          sfdx force:apex:test:run -u ${{ secrets.SFDC_USERNAME }} --resultformat human --codecoverage --outputdir test-results --wait 10
+          if grep -q "Fail" test-results/test-result-*.json; then
+            echo "Some Apex tests failed:"
+            cat test-results/test-result-*.json
+            exit 1
+          else
+            echo "All Apex tests passed successfully."
+          fi
 
+      - name: Check Code Coverage
+        run: |
+          COVERAGE=$(jq '.result.summary.coverage.coveredPercent' test-results/test-result-*.json)
+          if (( $(echo "$COVERAGE < 75" | bc -l) )); then
+            echo "Code coverage is below 75%: $COVERAGE"
+            exit 1
+          else
+            echo "Code coverage is sufficient: $COVERAGE"
+          fi
       # Authenticate to target org
       - name: "Authenticate to Org"
         env:
